name: stripe_payment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  popover: ^0.3.0+1
  cloud_firestore: ^4.17.3
  country_code_picker: ^3.0.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_stripe: ^10.1.1
  fluttertoast: ^8.2.5
  get_it: ^7.7.0
  http: ^1.2.1
  image_picker: ^1.1.1
  injectable: ^2.4.1
  lottie: ^3.1.0
  provider: ^6.1.2
  badges: ^3.1.2

dev_dependencies:
  build_runner: ^2.1.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/
    - asset/Lottie/
    - asset/icons/
    - asset/promotions/
    - asset/png/
