// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABkNtSqYZTk0eVNY6um0ZddLMIjHZBmNU',
    appId: '1:95966393253:web:b8e3e4cd7e99436407ae4c',
    messagingSenderId: '95966393253',
    projectId: 'foody-3313d',
    authDomain: 'foody-3313d.firebaseapp.com',
    storageBucket: 'foody-3313d.appspot.com',
    measurementId: 'G-20NFLMMT4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBin94icQDbKghiUv2AmbMwkfoMtoH2_yg',
    appId: '1:95966393253:android:5d4ce191449368b107ae4c',
    messagingSenderId: '95966393253',
    projectId: 'foody-3313d',
    storageBucket: 'foody-3313d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3x3dwsOYsapnRz7muxYEmG08PgZtvo-4',
    appId: '1:95966393253:ios:d1c285372ce85aab07ae4c',
    messagingSenderId: '95966393253',
    projectId: 'foody-3313d',
    storageBucket: 'foody-3313d.appspot.com',
    iosBundleId: 'com.ivan.stripePayment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3x3dwsOYsapnRz7muxYEmG08PgZtvo-4',
    appId: '1:95966393253:ios:789baf48314f0d6307ae4c',
    messagingSenderId: '95966393253',
    projectId: 'foody-3313d',
    storageBucket: 'foody-3313d.appspot.com',
    iosBundleId: 'com.example.stripePayment.RunnerTests',
  );
}
